### ISSUE TITLE
Claim middleware value not being read correctly

### ISSUE THREAD

**Issue by causingh** [corbosman/laravel-passport-claims#12]
```
Route::middleware(['client', 'claim:my-claim,foobar'])->get('my-protected-route', function () {
    return 'protected by claim with foobar as its value';
});
```
In the code snippet above, claim middleware is accepting all values which should not be.

**Comment by corbosman** [comment]
Hi, thanks for reporting this. You're right, i think somewhere along the lines the way the parameter is passed to the middleware changed. Can you try 3.0.1 and see if that fixes it for you?

**Comment by causingh** [comment]
Hi @corbosman this works fine now. Thank you.
