### ISSUE TITLE
Command "claim" is not defined.

### ISSUE THREAD

**Issue by aagjalpankaj** [corbosman/laravel-passport-claims#13]
When I execute `php artisan claim:generate Claims/CustomClaim` I get below error:
**There are no commands defined in the "claim" namespace.**

**Comment by corbosman** [comment]
Are you sure the package was installed/discovered correctly? Which version of laravel and this package is this?

```
$ php artisan claim:generate Foo/Bar
Claim created successfully.
```

**Comment by aagjalpankaj** [comment]
Thanks!
Solved by this - https://stackoverflow.com/questions/32396158/there-are-no-commands-defined-in-the-command-namespace-after-running-comman
Need to add `ClaimGenerator::class` in `kernel.php`.

**Comment by corbosman** [comment]
Hi that should not be necessary, this should all work out of the box. Look here, from a total new install:

```
$ laravel new foobar

Creating a "laravel/laravel" project at "./foobar"
.....

 $ composer require corbosman/laravel-passport-claims
Using version ^3.0 for corbosman/laravel-passport-claims
./composer.json has been updated
Running composer update corbosman/laravel-passport-claims
Loading composer repositories with package information
....

$ php artisan claim:generate Foo/Bar                          
Claim created successfully.
```

**Comment by aagjalpankaj** [comment]
That's not working at my end. Maybe be because I've lumen framework and I am using lumen-passport - https://github.com/dusterio/lumen-passport.
Does this package support lumen-passport?

**Comment by corbosman** [comment]
Ah that's very possible, my package is not made/tested for Lumen. if it works for you, great.

**Comment by aagjalpankaj** [comment]
When I do `php artisan vendor:publish --provider="CorBosman\Passport\ServiceProvider"` it says "Unable to locate publishable resources". Do you have any idea about it?

When I do `php artisan vendor:publish` it lists only below:
[0] Publish files from all providers and tags listed below
[1] Provider: Illuminate\Pagination\PaginationServiceProvider
[2] Provider: Laravel\Passport\PassportServiceProvider
[3] Tag: laravel-pagination
[4] Tag: passport-config
[5] Tag: passport-migrations
[6] Tag: passport-views
