### ISSUE TITLE
Doesn't support lumen-passport

### ISSUE THREAD

**Issue by aagjalpankaj** [corbosman/laravel-passport-claims#14]
Seems currently it doesn't support [lumen-passport](https://github.com/dusterio/lumen-passport). Would be good if we add support for it.
BTW, this is a really helpful package :)

**Comment by corbosman** [comment]
You should try if you just create your own config file, if it works at all. If so, it's just a matter of the config file template not installing.

**Comment by corbosman** [comment]
I'm not really that motivated in adding Lumen support. We don't have Lumen running internally anymore so testing it is a hassle. A PR is always welcome. I personally don't think Lumen really has a purpose anymore, but I totally understand other people might feel different. I think all that doesn't work is the packaging part, so publishing config etc. Just try making your own config and see.

**Comment by aagjalpankaj** [comment]
@corbosman - Resolved, thanks! I'll check for PR.
