### ISSUE TITLE
What I'm wrong ?

### ISSUE THREAD

**Issue by pbsweb** [corbosman/laravel-passport-claims#2]
Hi, your package is exactly what I need. I follow the simple installation guide but nothing happen. No claims add to to token and, just for test purpose, if I write in config an inexistant class name, I receive no error. It's seems that all package is totally ignored.
I'm trying to use in Laravel 7
Maybe I 've missed something ?
Thank you so much!

**Comment by corbosman** [comment]
Was the service provider added automatically?  If you do 'composer dump-autoload' do you see 'Discovered Package: corbosman/laravel-passport-claims'  ?

If you do see it, and you're using passport8 (which is all it supports right now), you may have to add some debug statements.

**Comment by pbsweb** [comment]
After config:cache now works perfectly :)
Thank you so much!!
