### ISSUE TITLE
limit the claims based on claims

### ISSUE THREAD

**Issue by chaotic98** [corbosman/laravel-passport-claims#20]
does this package have a feature that limits the claims based on scopes?
example: i have a scopes like "email", if i login with the scope "email" the package will only add user email claim, but if i have a scope with * it will add all user claims

**Comment by corbosman** [comment]
No, but you can just do that yourself. You have access to Laravel\Passport\Bridge\AccessToken class in your user claims. So just check the scopes on the token and add your claims or not. You can make your claims classes as elaborate as your want.

**Comment by chaotic98** [comment]
my code is like this
```
class UserClaim
{
    public function handle(AccessToken $token, $next)
    {
        $user = User::find($token->getUserIdentifier());
        $userPermissions= [];
        $token->addClaim('user', $user);

        return $next($token);
    }
}
```
with $token i can get scope with this method 
```
$scopes = $token->getScopes()
```
it can show all scopes 
![image](https://user-images.githubusercontent.com/61518809/214546197-af95617e-e1be-49df-833c-852334f96745.png)

but i cant get access in its properties
when i get identifiers it shows this error
```
 $a[0]->identifier

```

    "message": "Cannot access protected property Laravel\\Passport\\Bridge\\Scope::$identifier",

**Comment by corbosman** [comment]
```$token->getScopes()[0]->getIdentifier()```
