### ISSUE TITLE
[question] how Middleware handles claims datatypes

### ISSUE THREAD

**Issue by erikn69** [corbosman/laravel-passport-claims#26]
If we do 
```php
Route::middleware(['client', 'claim:1'])->get('my-protected-route', function () {
    return 'protected by claim with foobar as its value';
});
```
the value its gonna be a string, so if claim is an int, Are the values ​​not going to be the same? or token changes the int to string internally?

https://github.com/corbosman/laravel-passport-claims/blob/fec9244101a79e8258caa050baacf83d8559be7d/src/Http/Middleware/CheckForClaim.php#L42

**Comment by corbosman** [comment]
Hi, you're probably right it's better to use == instead of ===. I can't really think of a reason not to change it, you?

**Comment by erikn69** [comment]
Well, changing that breaks https://github.com/corbosman/laravel-passport-claims/pull/25

**Comment by erikn69** [comment]
@corbosman please review this commit https://github.com/corbosman/laravel-passport-claims/pull/25/commits/3f47c9ae6dea7769518f7466b2e9a97b8f01c69b
