### ISSUE TITLE
useAccessTokenEntity breaks passport compatibility 

### ISSUE THREAD

**Issue by erikn69** [corbosman/laravel-passport-claims#28]
- https://github.com/corbosman/laravel-passport-claims/commit/dfbb450febbd5a3c595c6e6e1dab17bb90243b17 **use builtin method**
https://github.com/corbosman/laravel-passport-claims/blob/fec9244101a79e8258caa050baacf83d8559be7d/src/ServiceProvider.php#L13

`useAccessTokenEntity`  was added on [passport/v11.8.3](https://github.com/laravel/passport/releases/tag/v11.8.3), https://github.com/laravel/passport/commit/587aa1460fb8a4ac24d042b68513ef86b78d760a, so this commit breaks compatibility with versions prior to version **11.8.3**
https://github.com/corbosman/laravel-passport-claims/blob/fec9244101a79e8258caa050baacf83d8559be7d/composer.json#L21

**Comment by corbosman** [comment]
Ah ok, didn't realize, I'll revert that change.  Thanks for noticing.

**Comment by corbosman** [comment]
Fixed in 1.5.1
