### ISSUE TITLE
Can not add iss claim

### ISSUE THREAD

**Issue by abublihi** [corbosman/laravel-passport-claims#32]
Hi @corbosman ,, thank you for the awesome package,,

i have an issue when trying to add `iss` claim,,

`Lcobucci\JWT\Token\RegisteredClaimGiven  Builder#withClaim() is meant to be used for non-registered claims, check the documentation on how to set claim "iss".`

Do you have an idea how to resolve this?

**Comment by corbosman** [comment]
Hi, this is currently not possible with this package. I use the withClaim call (see Lcobucci\JWT\Token), which specifically denies setting registered claims. It looks like that ISS claim is actually not set at all normally? If you look at the laravel code (using oauth2-server) it does:

```
    private function convertToJWT()
    {
        $this->initJwtConfiguration();

        return $this->jwtConfiguration->builder()
            ->permittedFor($this->getClient()->getIdentifier())
            ->identifiedBy($this->getIdentifier())
            ->issuedAt(new DateTimeImmutable())
            ->canOnlyBeUsedAfter(new DateTimeImmutable())
            ->expiresAt($this->getExpiryDateTime())
            ->relatedTo((string) $this->getUserIdentifier())
            ->withClaim('scopes', $this->getScopes())
            ->getToken($this->jwtConfiguration->signer(), $this->jwtConfiguration->signingKey());
    }
 ```
 
 It never calls IssuedBy. The only way to do this would be to add a way to call IssuedBy, but that's kind of a niche thing. You could fork my package and simply add it yourself.  Or try to make a PR.

**Comment by drmmr763** [comment]
@corbosman  also arrived here looking to add a way to add the `iss` claim to the jwt. 

Would you be open to doing something
1. adding a `issuedBy` class optional in the configuration?
2. calling that class's `handle` function from here https://github.com/corbosman/laravel-passport-claims/blob/master/src/AccessToken.php#L25 and passing it the builder?

Or something else I haven't thought of?

**Comment by drmmr763** [comment]
@corbosman  took a stab at it let me know your thoughts https://github.com/corbosman/laravel-passport-claims/pull/33
