### ISSUE TITLE
retrieve custom claims from refresh token

### ISSUE THREAD

**Issue by Maxwell2022** [corbosman/laravel-passport-claims#35]
When refreshing a token, `oauth2-server` (which Laravel uses in the background) [has a mechanism to retrieve old `scopes` claims from the token](https://github.com/thephpleague/oauth2-server/blob/0576f3920115d27edf661b70a784702d20f34b13/src/Grant/RefreshTokenGrant.php#L48-L56) so that you can just refresh the token without the need to know what is in the token itself.

It seems this package is only `adding` custom claims to an existing token (after the refresh has happened). This means that when you refresh a token, you cannot access the old token custom claims this package can add. It seems that you can only add claims to the newly refreshed token. Is that correct?

**Comment by corbosman** [comment]
I'm not sure. If that mechanism takes the scopes from the original token you'd think the added scopes are there as well right? I haven't really checked that.

**Comment by corbosman** [comment]
I see what the code does, i feel like it should be working but I guess it isn't? I'll try to do some tests later today or this weekend.

**Comment by Maxwell2022** [comment]
I'm not sure I was clear enough. What I meant is that when Passport issues the original token, you can add custom claims to the token. Which is fine, this is working great, you end up with a JWT token looking like this:

```json
{
   ...
   "sub": "1234",
   "scope": "can-read can-write",
   "foo": "bar"
}
```

`foo` is the custom claim we added when the token was originally issued.

When we are refreshing the token, it goes into the Laravel mechanism, calling `oatuh2-server` that returns a new refreshed token with the previous `scopes` untouched (unless you requested a new scope while refreshing).

But when we reach the custom claim `handle()` method, the token doesn't hold this old value of `foo` that was in the original token we are trying to refresh.

Hence my question. Does this package only **"adds"** custom claims each time a token is issued, without the ability to access the previous value of this custom claim (when refreshed)? If so, I think this should be documented. 

Thanks again :)

**Comment by corbosman** [comment]
I think there is a bit of confusion between accesstokens and refreshtokens. The accesstoken is what holds the scopes and claims, and it's what this package modifies to add custom claims. With the accesstoken oauth2 provides you with a refreshtoken that has a sole purpose, provide a new accesstoken. The refreshtoken does not contain scopes or claims. So when you refresh the accesstoken using the refreshtoken you provide a totally different token that does not contain any claims and thus no previous values to check.

**Comment by corbosman** [comment]
Actually, if you check the Refreshtoken it does contain the scopes assigned to the accesstoken, but no claims (not even the normal claims). It holds the scopes only to check if you're not suddenly trying to add scopes that weren't originally assigned. Not sure a refreshtoken can even hold claims. I've certainly never seen that.

{"client_id":"4","refresh_token_id":"713b84ad9694436e4a446f445e1a2bfa83b7918dea39afca69377b30591c3fdbc9b83a250abe33d7","access_token_id":"89507f11a4e14490f9d52799fb79e84a033b768f1995eb82a371b4cab2a68b4a64bb41fddeb90e94","scopes":["login","name","email","gravatar"],"user_id":1,"expire_time":1739194678}

**Comment by Maxwell2022** [comment]
Thanks, yes I think there is confusion hence my question.

According to [OAuth2](https://auth0.com/docs/secure/tokens#id-tokens), everything in the decoded JWT token is a claim. For example `sub` is a claim, `aud` is a claim, and `scopes` holds a collection of application `claims`. 

So my question remains the same. Is the assumption this package only adds `custom claim` to an already generated token? Meaning you do not have access to these **custom claims** in the refreshed token, or in the new access token created from the refresh token?

For instance, imagine someone authenticating. From the authentication context we can attach a list of accounts this user has access to. We call this custom claim `accountIds: [123, 456]` and send back the JWT token to the client. 

After a while, once the token expires, the client will attempt to refresh its token. However, when the server receives this refresh request, it doesn't know how to populate this `accountIds` custom claim. And because the refresh token is not providing it, then we cannot add the correct value the client expect.

**Comment by corbosman** [comment]
Hi, your assumption is correct. When laravel generates an accesstoken, this package hooks into the generation process and adds custom claims. It doesn't matter which API call generates the token. There are no custom claims in the refreshtoken. Look at the json i posted 2 comments above. That's literally the content of the refreshtoken.  It doesn't hold any of the normal claims that the accesstoken holds. They're 2 totally different things. 

When Laravel/League receives a refreshtoken api call, it just checks if you're not trying to add any new scopes to the token, and if not and the refreshtoken is valid, it generates a totally new accesstoken, which again passes through my package. I never see any old information about previously generated accesstokens. Any custom claims you added, you'll need to add exactly like you added them the first time using the information you had the first time.

**Comment by Maxwell2022** [comment]
Thanks for confirming and for you explanations. Everything makes sense to me :)
