### ISSUE TITLE
Add custom claim to a specific token

### ISSUE THREAD

**Issue by yusufbj** [corbosman/laravel-passport-claims#5]
Hi.

I have a case for a multi companies app:
1. One user has many companies:
2. Users login with password grant.
3. Afterwards, users will have to choose which company they will be using for the entire app flows.

Is it possible to add custom claim (chosen company id in this case), into the token generated by the password grant?

Thank you.

**Comment by corbosman** [comment]
Sure, just follow the readme on how to use the package to set claims on a token.  Any jwt library you use on an oauth2 client side should be able to read the claims.

**Comment by yusufbj** [comment]
Thanks for the reply.

Here is example of my code (select company api), the api will be called by a mobile app using password grant token, 

```php
    public function selectCompany(CompanySelectionRequest $request)
    {
        $userId = auth()->user()->getAuthIdentifier();
        $selectedCompanyId = $request->input('company_id');
        
        $this->companyService->validateUserCompany($userId, $selectedCompanyId);
        
        // TODO: How to add $selectedCompanyId into the password grant token that made this request?
        // TODO: Return token with $selectedCompanyId added into it.
    }
```

**Comment by corbosman** [comment]
If I understand you correctly you already have a token, and want to add claims to the token using an api call?  

If so, that's not something that's easily possible. You can't just add claims to an existing token, since the tokens are signed so they can't be messed with.  You'd have to generate a new token follow the passport docs. My package hooks into the passport token generation process to add claims.

**Comment by yusufbj** [comment]
You are correct. I will generate a new token, thanks, that answered my question. 

I have another questions for this topic:
1. For the same case, how to get the $selectedCompanyId inside the Claim Classes?
2. If I create one Claim Class, will it be hooked into every token generation process?

**Comment by corbosman** [comment]
Currently if you create a claim class, and add it to the claim config file, that class will be called every time a token is generated. You could of course put any kind of logic in the class to decide to add the claim or not. Don't forget, you have access to the Laravel\Passport\Bridge\AccessToken class as $token, so you can for instance get the current client using $token->getClient() if you want to limit the claims to a specific client.

**Comment by yusufbj** [comment]
Ok, thanks a lot for your help.

**Comment by primosoft-dev-2** [comment]
Hi, can you provide the code sample for this question's answer?

> 1. For the same case, how to get the $selectedCompanyId inside the Claim Classes?

**Comment by corbosman** [comment]
It depends on where $selectedCompanyId comes from. If it comes from the request, then you can get the request from the container using the request() helper method. If it comes from some other place, like a database, you just have to make those database calls.

**Comment by primosoft-dev-2** [comment]
Thanks for the reply.

for my app  $selectedCompanyId  comes from the request  and  the below line of code worked for me.
`  $selectedCompanyId = request('selectedCompanyId');`
