### ISSUE TITLE
How to set and get Claims from Controllers?

### ISSUE THREAD

**Issue by MarceloLuis1997** [corbosman/laravel-passport-claims#8]
Hi, first of all thanks for this package!
I'm testing it and I would like to know how can I set and get Claims from Laravel Controllers:

```
// How to add Claims in login?
public function login(Request $request)
{
    // some code
    $credentials = [
            'email' => $request->email,
            'password' => base64_decode($request->password)
        ];
    Auth::attempt($credentials);

    $user= $request->user();
    $token = $user->createToken('ACCESS_TOKEN')->accessToken;

    // At this point, how can I add custom Claims to my token?
    // I would like to do something like this:
    $token->addClaim('companyId', $request->company_id); // how can I do this through a Controller?
}

// How to get Claims?
public function me(Request $request)
{
    $user = $request->user();
    $token = $user->token();

    // How to get the companyId Claim set on login method?
    $companyId = $token->getClaim('companyId'); // How can I do this?
}
```

**Comment by corbosman** [comment]
If you use my package you don't use it like that. My package hooks into Laravel's token generation itself.  So the token you get back from your user->createToken() passes through my package.  But for that to happen to have to create a config, and a class to add the claims. That's described in my package documentation. Just follow it step by step.

**Comment by MarceloLuis1997** [comment]
@corbosman thanks for you reply. I looked at the docs, however I still don't understand how can I get a Claim value on a Controller function. I've tried `(new \Lcobucci\JWT\Parser())->parse($token);` but it don't work.

**Comment by corbosman** [comment]
First you install my package. You either pick ^1 or ^2 depending on your version of Passport.

```
composer require corbosman/laravel-passport-claims ^2
```

Then you create a claim class, pick a good name for it.

```
php artisan claim:generate Claims/CompanyId
```

Then you edit the class you just made, and add the data to the token as it shows you in the example code in the class.

```
    public function handle($token, $next)
    {
        $token->addClaim('companyId', request()->input('company_id');

        return $next($token);
    }
```

Next you create/edit the config file that tells passport to hook into my claim package.

```
php artisan vendor:publish --provider="CorBosman\Passport\ServiceProvider"
```

```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | JWT Claim Classes
    |--------------------------------------------------------------------------
    |
    | Here you can add an array of classes that will each be called to add
    | claims to the passport JWT token. See the readme for the interface that
    | these classes should adhere to.
    |
    */
    'claims' => [
        App\Claims\CompanyId::class
    ]
];
```

Then you're done. Now when you create a token using passport, if all goes well it should have the company id claim attached to it.

**Comment by MarceloLuis1997** [comment]
Hello @corbosman , thanks for your help, I actually did this steps and it worked well, the `companyId` was successfully attached to the token, but my question is: how can I get the companyId Claim value back? 

For example, in my controller, how can I get the companyId Claim value?

**Comment by corbosman** [comment]
You can see how I do that in the tests. Either for version 1 or version 2.

```https://github.com/corbosman/laravel-passport-claims/blob/1.7.1/tests/AccessTokenClaimTest.php```
```https://github.com/corbosman/laravel-passport-claims/blob/2.0.0/tests/AccessTokenClaimTest.php```

basically you just parse the token with Lcobucci\JWT\Parser and then you can use a method to get claims from the token.

**Comment by MarceloLuis1997** [comment]
Nice, it worked! This is how I did it, in case of someone need it:

```
$jwt = \Lcobucci\JWT\Configuration::forUnsecuredSigner()->parser()->parse($tokenString);
$companyId = $jwt->claims()->get('companyId');
```
